version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0 
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for this example
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp #for udp logs
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    environment:
      FLUENTD_CONF: fluentd.conf
      FLUENT_ELASTICSEARCH_HOST: elasticsearch
      FLUENT_ELASTICSEARCH_PORT: 9200
      FLUENT_ELASTICSEARCH_SCHEME: http
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    # volumes:
    #   - ./nginx/conf:/etc/nginx/conf.d
    #   - ./nginx/log:/var/log/nginx
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx

volumes:
  esdata: